### PR TITLE
Remove remaining js gettext call

### PR DESCRIPTION
**Pull request by soriat**
[#21012](https://github.com/iFixit/ifixit/pull/21012) in the iFixit repo removes the php version of `_js`

This pull replaces that instance with the new js version

Closed: https://github.com/iFixit/ifixit/issues/21045

### CODE REVIEW

**Comment by archive64** [comment]
Do you need to make the same changes in the non-built files? I assume this file is generated somehow?

**Comment by soriat** [comment]
I almost got the commit out before your comment, but you were too fast!

**Comment by archive64** [comment]
CR 👍

**Comment by archive64** [comment]
Haha :)

**Comment by danielbeardsley** [comment]
CR 👍

**Pull request merged**
