### PR TITLE
Fix XSS vulnerability by escaping user input in field templates

### PR DESCRIPTION
**Pull request by andrewjpiro**
This escapes some remaining instances of user input that we display in field templates. Most of the places we display user input were already escaped but a pen test found that the label field in some of the fields was vulnerable. QA later found that the options field was also vulnerable. While I was fixing those I did a quick double check and couldn't find anywhere else in the fields that we use. I also double checked that we do properly escape these fields when we display them in datacapture.

After these changes you can make a beautiful form like this:
Screenshot 2022-03-17 160627

Closes: #https://github.com/iFixit/dozuki/issues/3018

### CODE REVIEW

**Comment by hackalot805** [comment]
I'm confused... not all that familiar with this repo.  How did you make changes to `main-built.js`?  Are we missing a commit on a source file?  How did you build that?  I made changes to `assets/js/models/snippet.js` a while back... which seemed to work, but now I think I see my changes in your updated `main-built.js`?

EDIT: Oh, I see the build command in the original docs... `r.js -o assets/js/lib/build.js`... is that what you used?

**Comment by andrewjpiro** [comment]
@hackalot805 There's a Makefile in this repo. I just ran `make`. That's how I tested my changes so I assumed I needed to commit that built file.

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by hackalot805** [comment]
CR 💀

**Comment by PanzerKnackers** [comment]
dev_block 🦚 

Looks like simply adding a `</textarea>` to any of these datacapture fields will allow you to run a script. (This includes Text Input, Numeric Input, Multi-line Text Area, And Checkbox. The original issue stated these were not a problem.)


<details><summary>Radio buttons</summary>

main_large

image

</details>

<details><summary>Before</summary>

image

</details>

<details><summary>After</summary>

image

</details>

**Comment by andrewjpiro** [comment]
@PanzerKnackers good catch. The issue here is that we were escaping input when rendering the little snippets of the form but not in the popover where you can edit those values. My latest commit escapes the input in the popover form so now you shouldn't be able to get any js to run.

un_dev_block :boom:

**Comment by hackalot805** [comment]
CR 💀

**Comment by PanzerKnackers** [comment]
QA 🦚 

Input is properly escaped on the popover form:

<details open><summary>Screenshots</summary>

image

image

</details>

**Comment by rjmccluskey** [comment]
CR 🍻

**Pull request merged**
