### PR TITLE
Form Builder: Make all labels textareas

### PR DESCRIPTION
**Pull request by andrewjpiro**
We already made this change for radio buttons [here](https://github.com/iFixit/Bootstrap-Form-Builder/pull/14) since we wanted them to have a max character limit of 255. Now we want this change for all the inputs.

QA
===
- Setup in 3P/Bootstrap-Form-Builder:
   - `git pull` and `checkout` this branch
   - Run `make`
- Add one of every input type to a datacapture form.
- Verify they all have textareas for the "Label" field.

Part of iFixit/dozuki#2010.

### CODE REVIEW

**Comment by hackalot805** [comment]
LGTM CR 💀

**Comment by rjmccluskey** [comment]
CR 🍻

**Comment by JRodger312** [comment]
Forms are not currently rendering with their input labels converted to inputs besides radio buttons.

dev_block 🍔

**Comment by JRodger312** [comment]
image

image

**Comment by JRodger312** [comment]
un_dev_block 🍔.  Checked out the wrong directory...

All labels now have textarea inputs and can display 255 characters.

**Comment by JRodger312** [comment]
QA 🍔

**Pull request merged**
