### PR TITLE
Add Document upload form builder control

### PR DESCRIPTION
**Pull request by rjmccluskey**
Background
--

Part of https://github.com/iFixit/dozuki/issues/2334

This adds an input control for document uploads to the step form builder. It's basically a copy of the image and video inputs.

QA
--

This will be QA'd as part of the work on the ifixit repo that fully integrates document uploads. qa_req 0

### CODE REVIEW

**Comment by rjmccluskey** [comment]
deploy_block 🍻

I will merge this when the full feature on the ifixit repo is completed. I want to make sure we don't accidentally introduce this form control before it is ready to be used.

**Comment by andrewjpiro** [comment]
CR :boom:

**Comment by bcooper94** [comment]
CR 👍

**Comment by rjmccluskey** [comment]
Will merge this once https://github.com/iFixit/ifixit/pull/35553 merges

**Comment by rjmccluskey** [comment]
Actually it looks like I'm forced to merge this otherwise it causes a build failure on the other pull.
```
1) GitSubmodulesLineageTest::testEnforceSubmoduleLineage
'3P/Bootstrap-Form-Builder' changed to a ref that does not have origin/master as a descendant!
Please reference a submodule commit that is an ancestor of upstream master!

* If origin/master is not the standard upstream branch, please add or update the
mainline branch name in NON_MASTER_BRANCHES for the submodule. Ensure that
submodule commits reference ancestors of well known mainline branches.
```

un_deploy_block 🍻

**Pull request merged**
